services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb/.
    env_file : .env
    volumes : 
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - cmunoz-g
    restart: always
  
  wordpress:
    container_name: wordpress
    build: requirements/wordpress/.
    env_file : .env
    volumes:
      - wordpress:/var/www/html
    expose:
      - "9000"
    depends_on:
      - mariadb
    networks:
      - cmunoz-g
    restart: on-failure
  
  nginx:
    container_name: nginx
    build: requirements/nginx/.
    volumes:
      - wordpress:/var/www/html
    ports :
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - cmunoz-g
    restart: on-failure

# VERY IMPORTANT: make sure the volumes are completely removed (sudo) before make re

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vboxuser/Ivolumes/mariadb #/home/cmunoz-g/Ivolumes/mariadb 
    name: mariadb
    labels:
    - "purpose=database"
    - "project=inception"

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vboxuser/Ivolumes/wordpress # /home/cmunoz-g/Ivolumes/wordpress 
    name: wordpress
    labels:
    - "purpose=web"
    - "project=inception"

networks:
  cmunoz-g:
    driver: bridge