services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443" #cambiar a https
    volumes:
      - website:/var/www/html
    networks:
      - inception

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    volumes:
      - website:/var/www/html
    networks:
      - inception
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception

volumes:
  website:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/cmunoz-g/Ivols/website
    name:
      website
  
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/cmunoz-g/Ivols/database

networks:
  inception:
    driver: bridge